#### Atividade Lab 2

Arquivo 1 - Antes da edição (L2_cal.py)

In [ ]:
import cv2
import numpy as np
import os
import glob
 
# Defining the dimensions of checkerboard
CHECKERBOARD = (6,9)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 
 
 
# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None
 
# Extracting path of individual image stored in a given directory
images = glob.glob('*.jpg')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
     
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
    cv2.imshow('img',img)
    cv2.waitKey(0)
 
cv2.destroyAllWindows()
 
h,w = img.shape[:2]
 
"""
Performing camera calibration by 
passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the 
detected corners (imgpoints)
"""
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
 
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)


Arquivo 2 - Antes da edição (L2_chess.py)

In [ ]:
import numpy as np
import cv2 as cv

cap = cv.VideoCapture(0)

if not cap.isOpened():
    print("Cannot open camera")
    exit()
    
i = 0
    
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    
    # Display the resulting frame
    cv.imshow('frame', frame)

    # Save on "s" key or exit on "q"
    k = cv.waitKey(1) 
    if  k == ord('s'):
        cv.imwrite("frm"+str(i)+".jpg",frame)
        i = i + 1
        print("frame", i)
    elif k == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv.destroyAllWindows()


##### Parte 1:

Para a primeira etapa foram disponibilizados 3 links referentes a documentações contendo excplicações teóricas sobre tratamento de imagem.

Link 1: https://learnopencv.com/geometry-of-image-formation/

Link 2: https://learnopencv.com/camera-calibration-using-opencv/

Link 3: https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html



(descrever a que os textos se referem fazendo um resumo.)

##### Parte 2

Nessa etapa faremos a calicação da câmera baseado no "Link 2" e utilizando o arquivo L2_cal.py


Para isso é necessário que tenhamos conhecimento dos parametros utilizados pela câmera, para que possamos transformar as imagens de 3D para os pixels em 2D.


Esses parametros são divididos em duas partes, internos e externos.

A)

Matriz intrinsica da câmera:

Camera matrix : 

[[536.07343567   0.         342.37038373]
 [  0.         536.01635124 235.53685496]
 [  0.           0.           1.        ]]


 dist : 

[[-0.26509012 -0.04674346  0.00183301 -0.00031472  0.25231495]]

(array([[-0.3746336 ],
       [ 0.06982835],
       [-0.01937108]]), array([[ 0.05280146],
       [-0.60171821],
       [-0.18453822]]), array([[-0.34698248],
       [-0.06738503],
       [-1.20088995]]), array([[ 0.1972109 ],
       [-0.42009945],
       [-0.1949708 ]]), array([[ 0.4828725 ],
       [-0.17036999],
       [-1.40740334]]), array([[-0.10141611],
       [ 0.32034835],
       [ 0.3147293 ]]), array([[-0.08398745],
       [ 0.34802803],
       [-1.54244125]]), array([[-0.22584694],
       [ 1.0155114 ],
       [-2.79470629]]), array([[-0.47359527],
       [ 0.08970849],
       [-0.22605977]]), array([[-0.35339069],
       [ 0.24071879],
       [ 0.20970029]]), array([[ 0.49542331],
       [ 0.11948824],
       [-0.29675962]]), array([[0.06525918],
       [0.44701849],
       [0.10800011]]), array([[-0.27527337],
       [ 0.10123358],
       [-1.56296566]]))
tvecs : 

(array([[-2.95848507],
       [-3.94417917],
       [13.21423801]]), array([[-2.16838614],
       [-3.50011104],
       [10.73694876]]), array([[-3.42743405],
       [ 0.48738235],
       [11.56153534]]), array([[-2.67642764],
       [-3.18945558],
       [10.58262296]]), array([[-3.50264504],
       [ 1.6159546 ],
       [11.97222434]]), array([[-3.72585127],
       [-4.31084787],
       [17.2043959 ]]), array([[-2.96218139],
       [ 0.57159003],
       [16.83013784]]), array([[ 2.53399669],
       [ 4.3199921 ],
       [13.71918905]]), array([[-2.5179161 ],
       [-3.4306905 ],
       [12.85702176]]), array([[-1.59003858],
       [-4.31771177],
       [14.01040699]]), array([[-3.40557301],
       [-2.4104226 ],
       [12.58706846]]), array([[ 2.207421  ],
       [-3.21446546],
       [15.60125332]]), array([[-3.99387882],
       [ 2.27704401],
       [12.68878148]]))


Para resolução do item acima foi necessário apontar a variavel img para os arquivos de amostras.

##### Parte 2 - B



Código alterado para execução da parte 2.

In [ ]:
    # Display the resulting frame
    cv.imshow('frame', frame)

    # Save on "s" key or exit on "q"
    k = cv.waitKey(1) 
    if  k == ord('s'):
        cv.imwrite("./grupo-samples/lucas"+str(i)+".jpg",frame)
        i = i + 1
        print("frame", i)
    elif k == ord('q'):
        break

Caminho dos arquivos da parte 2:
./grupo-samples/

Arquivo alterado para execução do item B, utilizando a nossa imagem do tabuleiro.

In [ ]:
import cv2
import numpy as np
import os
import glob
 
# Defining the dimensions of checkerboard
CHECKERBOARD = (6,8)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 
 
 
# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None
 
# Extracting path of individual image stored in a given directory
images = glob.glob('./grupo-samples/*.jpg')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
     
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
    cv2.imshow('img',img)
    cv2.waitKey(0)
 
cv2.destroyAllWindows()
 
h,w = img.shape[:2]
 
"""
Performing camera calibration by 
passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the 
detected corners (imgpoints)
"""
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
 
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)

Parametros medidos no item B parte 2:

Camera matrix : 

[[691.29939128   0.         326.80276268]
 [  0.         692.13240307 219.64457563]
 [  0.           0.           1.        ]]
dist : 

[[ 1.21164755e-01 -1.80341820e+00  1.64363312e-04 -7.60266984e-03
   9.12197319e+00]]
rvecs : 

(array([[ 0.34030661],
       [-0.64395203],
       [ 1.45726228]]), array([[ 0.66439822],
       [-0.82912519],
       [-1.08610413]]), array([[ 0.64222347],
       [-0.6413235 ],
       [ 1.46444406]]), array([[-0.1302544 ],
       [ 0.10646706],
       [-1.0387285 ]]), array([[-0.82851336],
       [ 0.6535799 ],
       [ 1.36696742]]), array([[-0.90199068],
       [ 0.24249242],
       [ 1.32461194]]), array([[-0.51136924],
       [-0.06175017],
       [-0.23997589]]), array([[-0.11743436],
       [ 0.21082132],
       [ 1.50923599]]), array([[-0.73333152],
       [-0.41849031],
       [-0.63287277]]), array([[-0.15481039],
       [-0.59235345],
       [ 1.29567114]]), array([[ 0.26000572],
       [-0.20826415],
       [ 0.06725556]]), array([[-0.68644636],
       [ 0.32961181],
       [ 1.4217883 ]]), array([[ 0.01649892],
       [-0.14198133],
       [ 1.57474915]]), array([[ 0.05190661],
       [-0.69807807],
       [ 0.82150603]]))
tvecs : 

(array([[ 3.04307359],
       [-1.22388435],
       [16.05929538]]), array([[-3.02659696],
       [ 2.23760102],
       [12.44878562]]), array([[ 3.50754501],
       [-1.62849374],
       [13.4914934 ]]), array([[-4.48606727],
       [-0.22691993],
       [18.24453401]]), array([[ 3.2408679 ],
       [-2.20850987],
       [16.48658753]]), array([[ 2.05913497],
       [-1.41699544],
       [18.89359878]]), array([[-1.85223215],
       [-2.10454171],
       [18.48411152]]), array([[ 3.67876371],
       [-2.25851861],
       [14.73231102]]), array([[-3.79184025],
       [-2.11379481],
       [16.44896473]]), array([[ 1.92157795],
       [-2.84557839],
       [18.17655542]]), array([[-2.18481237],
       [-2.24779745],
       [16.76734773]]), array([[ 2.65321446],
       [-3.36055116],
       [18.25509596]]), array([[ 2.78757729],
       [-2.13258889],
       [16.36612542]]), array([[ 1.27114255],
       [-3.7317837 ],
       [18.5421511 ]]))

##### Parte 2 - C

Para esta etapa foram utilizadas imagens capturadas pela câmera do celular com uma resolução bem maior do que a utilizada anteriormente.

Camera matrix : 

[[690.57939917   0.         459.70860971]
 [  0.         689.18030163 422.86297081]
 [  0.           0.           1.        ]]
dist : 

[[-0.19201434  0.36787535 -0.01442795  0.00406974 -0.49560428]]
rvecs : 

(array([[-0.26376473],
       [ 0.24299112],
       [-1.21089966]]), array([[-0.58171941],
       [-0.45530289],
       [-1.38013168]]), array([[ 0.15662042],
       [-0.02658416],
       [ 1.58554542]]), array([[-0.16304176],
       [-0.11128085],
       [ 0.54745919]]), array([[ 0.37858058],
       [-0.29571776],
       [-1.01696836]]), array([[-0.59293558],
       [ 0.0329549 ],
       [ 0.52883148]]), array([[-1.04437208],
       [-0.38558207],
       [-0.80975221]]), array([[-0.5780895 ],
       [-0.09542955],
       [-0.69297084]]), array([[-0.5892605 ],
       [-0.21640485],
       [ 1.39271697]]), array([[-0.28140131],
       [ 0.43286906],
       [-0.09606854]]), array([[ 0.59169014],
       [-0.92852142],
       [ 0.08089715]]), array([[-0.15918898],
       [ 0.0091384 ],
       [ 0.01369549]]), array([[-0.23854841],
       [-0.18296492],
       [ 1.44317065]]))
tvecs : 

(array([[-3.26034657],
       [ 0.2235424 ],
       [11.34624057]]), array([[-3.33036217],
       [ 0.48757511],
       [ 7.85922378]]), array([[ 3.62255746],
       [-3.58924109],
       [ 8.6545276 ]]), array([[-0.98219389],
       [-3.44440619],
       [11.14335641]]), array([[-4.65145051],
       [-0.42435246],
       [11.58432783]]), array([[-1.0077882 ],
       [-3.88586167],
       [14.83635978]]), array([[-6.28329829],
       [ 0.30773385],
       [11.65832076]]), array([[-3.62865469],
       [-2.43498695],
       [11.91371477]]), array([[ 2.16386303],
       [-4.98976656],
       [14.613801  ]]), array([[-2.79608728],
       [-2.63015994],
       [12.60429919]]), array([[-1.7470227 ],
       [-1.19984893],
       [ 5.95174709]]), array([[-3.19742441],
       [-3.6128068 ],
       [11.51175185]]), array([[ 1.92771389],
       [-1.93490582],
       [13.56333082]]))

